env:
- DOCKER_COMPOSE_VERSION=3.7
addons:
  ssh_known_hosts: 157.230.182.92
script:
- docker build .
before_install:
- openssl aes-256-cbc -K $encrypted_d82f9d7a2831_key -iv $encrypted_d82f9d7a2831_iv
  -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
- rvm install 2.2.2
- chmod 600 ~/.ssh/travis_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: ""./scripts/deploy.sh"
  on:
    branch:
    - master
    - Firbase-Test
