cache:
    yarn: true
    directories:
    - node_modules
script:
    - yarn
    - export REACT_APP_ENV=production
    - yarn build
    - yarn test
deploy:
    provider: firebase
    token:
        secure: fmQh8sialox2fhFsTClukIwD9kVac5cv628KwgNWp3+1BlSlzFnTi0gi1odfFtFV89NSEtFc75yMu7pQw3hrFQVGSQxsXRwWhbslL8+j8OqOk7RGX2ILY5ue4AYtm7TQiE8LlRknyq8EhHpNzPvZTcfEoNhTMYUGE/glhi02dkbWclGQ+lx+SQlnQBzCbX7MYFEBthDQiEEZ0N4lLFU7Lr2x77ZExiflyRRgb593H/r8lsfGqQiLQtDzTOE4qSi5+PuYrZfaNdW+du9pzgmhGnBeM2ZoFWZX96ZUOs3UaKrTbkkRZtky9wB0PWubUW8cWk91Qnt24GYvS/isOV7/wK2/WA6Ig7eTZIRjTn7GuItA0AMeuYDBlnnCpA1TDaORt0uBA4s49yS/Z1vEEf/YAJQPf+hueglY+B72MmNq0DM3FlciMU3sJZxhRcdICSFa4psfCIb9qSlJIL9TE8MAsqSUBrASjdcUiN+TgjjFge8CxGTdI4nRwg4Hj6NemQkpKKiDXBTXfSR/1FaxSg75VF/rHZeu77w8dWBB5gBxfDwePSypyGjQP4E/Qyo+OTHETkKyns39sO3SH8FF0si22uud0ZmSTrnNwr38NhqZ24yXfsJgJdUImX0ze9GM6nAFmX3imsE6E9A+K32pAr7g1g4RApRnCXIGd2GfaVAX1u8=
    on:
        branch: FirebaseDeploy
    project: production
