version: '3'

services:
  cgwebapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment: 
      - NODE_ENV=production
      - SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME=${SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME}
      - FIREBASE_CLIENT_CONFIG=${FIREBASE_CLIENT_CONFIG}

