version: '3'

services:
    cgwebapp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:3000"
        environment:
            - NODE_ENV=$NODE_ENV
