version: '3'

services:
  cgwebapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
      - NODE_ENV=test
      - SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME=${SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME}
      - FIREBASE_CLIENT_CONFIG=${FIREBASE_CLIENT_CONFIG}
