version: '3'

services:
  cgwebapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    environment:
      - NODE_ENV=$NODE_ENV
      - DEVELOPMENT_SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME=$DEVELOPMENT_SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME
      - DEVELOPMENT_DATABASE_URL=$DEVELOPMENT_DATABASE_URL
      - TESTING_SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME=$TESTING_SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME
      - TESTING_DATABASE_URL=$TESTING_DATABASE_URL
      - PRODUCTION_SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME=$PRODUCTION_SERVICE_ACCOUNT_PRIVATE_KEY_FILE_NAME
      - PRODUCTION_DATABASE_URL=$PRODUCTION_DATABASE_URL
