version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: production_nginx
        volumes:
            - ./productionConfig/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/:/etc/letsencrypt/
        environment:
            - ENV=production
            - APPLICATION_URL=http://cgwebapp
        ports:
            - 80:80
            - 443:443

    cgwebapp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000"
        environment:
            - NODE_ENV=$NODE_ENV
