const SET_USER = 'SET_USER';
const LISTEN_FOR_USER = 'LISTEN_FOR_USER';
const GOOGLE_SIGN_IN = 'GOOGLE_SIGN_IN';
const GOOGLE_SIGNED_IN = 'GOOGLE_SIGNED_IN';
const SIGN_OUT = 'SIGN_OUT';
const SIGNED_OUT = 'SIGNED_OUT';

export default {
    SET_USER,
    LISTEN_FOR_USER,
    GOOGLE_SIGN_IN,
    GOOGLE_SIGNED_IN,
    SIGN_OUT,
    SIGNED_OUT
}
